name: ssss
version: 0.1.0

ghc-options: -Wall

dependencies:
  - base

default-extensions:
  - DeriveGeneric
  - LambdaCase
  - OverloadedStrings
  - NoImplicitPrelude
  - ViewPatterns

library:
  source-dirs: src
  dependencies:
    - base64-bytestring
    - bytestring
    - cryptohash-sha256
    - secret-sharing
    - utf8-string

executables:
  ssss:
    source-dirs: app
    main: Main.hs
    dependencies:
      - base64-bytestring
      - bytestring
      - optparse-generic
      - QuickCheck
      - secret-sharing
      - ssss
      - text

tests:
  props:
    source-dirs: test
    main: Props.hs
    dependencies:
      - bytestring
      - QuickCheck
      - ssss
      - secret-sharing
      - text
