name: ssss
version: 0.1.0

ghc-options: -Wall

default-extensions:
  - DeriveFunctor
  - DeriveGeneric
  - FunctionalDependencies
  - LambdaCase
  - OverloadedStrings
  - PatternSynonyms
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - ViewPatterns

dependencies:
  - base
  - bytestring
  - secret-sharing
  - text

library:
  source-dirs: src
  dependencies:
    - base64-bytestring
    - cryptohash-sha256 # TODO replace with cryptonite
    - cryptonite
    - exceptions
    - memory
    - streaming
    - streaming-bytestring
    - utf8-string

executables:
  ssss:
    source-dirs: app
    main: Main.hs
    dependencies:
      - cryptonite
      - optparse-generic
      - QuickCheck
      - resourcet
      - ssss
      - streaming-bytestring

tests:
  props:
    source-dirs: test
    main: Props.hs
    dependencies:
      - QuickCheck
      - ssss
