name: sss
version: 0.1.0

ghc-options: -Wall

default-extensions:
  - DeriveFunctor
  - DeriveGeneric
  - FlexibleInstances
  - FunctionalDependencies
  - LambdaCase
  - OverloadedStrings
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - RankNTypes
  - ViewPatterns

dependencies:
  - base
  - bytestring
  - secret-sharing
  - text

library:
  source-dirs:
    - src
    - src/extra
  dependencies:
    - base64-bytestring
    - cryptohash-sha256 # TODO replace with cryptonite
    - cryptonite
    - exceptions
    - memory
    - streaming
    - streaming-bytestring
    - utf8-string

executables:
  sss:
    source-dirs: app
    main: Main.hs
    dependencies:
      - ansi-wl-pprint
      - cryptonite
      - optparse-applicative >= 0.14.0.0
      - QuickCheck
      - resourcet
      - sss
      - streaming-bytestring
      - unix

tests:
  props:
    source-dirs: test
    main: Props.hs
    dependencies:
      - QuickCheck
      - sss
